AWSTemplateFormatVersion: '2010-09-09'

Description: Creates a role that can be used to enable IOT logging

Resources:
  IoTLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:PutMetricFilter
                  - logs:PutRetentionPolic
                Resource: '*'
          PolicyName: 'IoTLogRolePolicy'
                
Outputs:
  IoTLogRole:
    Description: The ARN of Role that IoT can assume to send logs to CloudWatch
    Value: !GetAtt 'IoTLogRole.Arn'
