AWSTemplateFormatVersion: '2010-09-09'
Description: Creates required AWS resources to allow an AWS IoT button to send information
  through an Amazon Simple Notification Service (Amazon SNS) topic to an email address.
Parameters:
  IoTButtonDSN:
    Type: String
    AllowedPattern: G030[A-Z][A-Z][0=9][0-9][0-9][0-5][0-9][1-7][0-9A-HJ-NP-X][0-9A-HJ-NP-X][0-9A-HJ-NP-X][0-9A-HJ-NP-X]
    Description: The device serial number (DSN) of the AWS IoT Button. This can be
      found on the back of the button. The DSN must match the pattern of 'G030[A-Z][A-Z][0=9][0-9][0-9][0-5][0-9][1-7][0-9A-HJ-NP-X][0-9A-HJ-NP-X][0-9A-HJ-NP-X][0-9A-HJ-NP-X]'.
  CertificateARN:
    Type: String
    Description: The Amazon Resource Name (ARN) of the existing AWS IoT certificate.
  ButtonListenerLambdaArn:
    Type: String
Resources:
  IoTThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: !Join
        - ''
        - - iotbutton_
          - !Ref 'IoTButtonDSN'
  IoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: iot:Publish
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:iot:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - :topic/iotbutton/
                - !Ref 'IoTButtonDSN'
  IoTPolicyPrincipalAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref 'IoTPolicy'
      Principal: !Ref 'CertificateARN'
  IoTThingPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      Principal: !Ref 'CertificateARN'
      ThingName: !Ref 'IoTThing'

  IoTTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: !Join
        - ''
        - - iotbutton_
          - !Ref 'IoTButtonDSN'
      TopicRulePayload:
        Actions:
          - Lambda:
              FunctionArn: !Ref 'ButtonListenerLambdaArn'
        AwsIotSqlVersion: '2015-10-08'
        RuleDisabled: false
        Sql: !Join
          - ''
          - - SELECT * FROM 'iotbutton/
            - !Ref 'IoTButtonDSN'
            - ''''
