AWSTemplateFormatVersion: '2010-09-09'

Description: Creates required SNS topics to support manual actions from CodePipeline and an IoT Button

Resources:
  PipelineListenerTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AWS Code Pipeline Notification
  PipelineListenerTopicRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Join
                  - ''
                  - - 'arn:aws:sns:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':'
                    - !Ref 'PipelineListenerTopic'
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Join
                  - ''
                  - - 'arn:aws:logs:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':*'
              # this is okay for now, but when we merge the templates together, this should refer to the lambda function's logs specifically
              - Effect: Allow
                Action: 
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Join
                  - ''
                  - - 'arn:aws:logs:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':*'
          PolicyName: 'PipelineListenerTopicRolePolicy'
  CodePipelineSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AWS CodePipeline Manual Approval Notification
Outputs:
  PipelineListenerTopic:
    Description: The SNS Topic the Button will push to
    Value: !Ref PipelineListenerTopic
  PipelineListenerTopicRole:
    Description: The ARN of Role of the Topic the Button will push to
    Value: !GetAtt 'PipelineListenerTopicRole.Arn'
