AWSTemplateFormatVersion: '2010-09-09'

Description: Creates required SNS topics to support manual actions from CodePipeline and an IoT Button

Resources:
  ButtonListenerTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AWS IoT Button Press Notification
  ButtonListenerTopicRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Join
                  - ''
                  - - 'arn:aws:sns:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':'
                    - !Ref 'ButtonListenerTopic'
          PolicyName: 'ButtonListenerTopicRolePolicy'
  CodePipelineSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AWS CodePipeline Manual Approval Notification
